# Generated by Django 3.1.2 on 2020-10-05 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ejes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=20)),
                ('altura', models.CharField(max_length=10)),
                ('modelo', models.CharField(max_length=5)),
                ('color', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Rodamientos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=20)),
                ('dureza', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ruedas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=20)),
                ('medida', models.CharField(max_length=10)),
                ('dureza', models.CharField(max_length=5)),
                ('color', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tabla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('medida', models.CharField(max_length=30)),
                ('concavo', models.CharField(max_length=10)),
                ('marca', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Precios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precios', models.IntegerField(default=0)),
                ('ejes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skateez.ejes')),
                ('rodamientos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skateez.rodamientos')),
                ('ruedas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skateez.ruedas')),
                ('tabla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skateez.tabla')),
            ],
        ),
    ]
