# Generated by Django 3.1.2 on 2020-10-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skateez', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejes',
            name='Precio',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='rodamientos',
            name='Precio',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='ruedas',
            name='Precio',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='tabla',
            name='Precio',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
