# Generated by Django 3.1.2 on 2020-10-05 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skateez', '0002_auto_20201005_1937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ejes',
            options={'verbose_name_plural': 'Ejes'},
        ),
        migrations.AlterModelOptions(
            name='precios',
            options={'verbose_name_plural': 'Precios'},
        ),
        migrations.AlterModelOptions(
            name='rodamientos',
            options={'verbose_name_plural': 'Rodamientos'},
        ),
        migrations.AlterModelOptions(
            name='ruedas',
            options={'verbose_name_plural': 'Ruedas'},
        ),
        migrations.AlterModelOptions(
            name='tabla',
            options={'verbose_name_plural': 'Tabla'},
        ),
    ]
