# Generated by Django 3.1.2 on 2020-10-06 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skateez', '0003_auto_20201005_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precios',
            name='ejes',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='skateez.ejes'),
        ),
        migrations.AlterField(
            model_name='precios',
            name='rodamientos',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='skateez.rodamientos'),
        ),
        migrations.AlterField(
            model_name='precios',
            name='ruedas',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='skateez.ruedas'),
        ),
        migrations.AlterField(
            model_name='precios',
            name='tabla',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='skateez.tabla'),
        ),
    ]
