# Generated by Django 3.1.2 on 2020-10-06 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skateez', '0005_auto_20201006_1907'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Precios',
            new_name='Pedidos',
        ),
        migrations.AlterModelOptions(
            name='pedidos',
            options={'verbose_name_plural': 'Pedidos'},
        ),
    ]
