# Generated by Django 3.1.2 on 2020-10-06 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skateez', '0006_auto_20201006_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='ejes',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='precios',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='rodamientos',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='ruedas',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='tabla',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='numero_pedido',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skateez.usuario'),
        ),
    ]
