# Generated by Django 3.1.2 on 2020-10-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skateez', '0008_auto_20201013_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejes',
            name='Cantidad',
            field=models.IntegerField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='rodamientos',
            name='Cantidad',
            field=models.IntegerField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='ruedas',
            name='Cantidad',
            field=models.IntegerField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='tabla',
            name='Cantidad',
            field=models.IntegerField(default='0', max_length=10),
        ),
    ]
