# Generated by Django 3.1.2 on 2020-10-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skateez', '0009_auto_20201013_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(max_length=30),
        ),
    ]
