# Generated by Django 3.1.2 on 2020-10-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skateez', '0010_auto_20201013_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejes',
            name='disponible',
            field=models.BooleanField(null='false'),
            preserve_default='false',
        ),
        migrations.AddField(
            model_name='rodamientos',
            name='disponible',
            field=models.BooleanField(null='false'),
            preserve_default='false',
        ),
        migrations.AddField(
            model_name='ruedas',
            name='disponible',
            field=models.BooleanField(null='false'),
            preserve_default='false',
        ),
        migrations.AddField(
            model_name='tabla',
            name='disponible',
            field=models.BooleanField(null='false'),
            preserve_default='false',
        ),
    ]
