# Generated by Django 3.1.2 on 2020-10-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skateez', '0011_auto_20201013_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='ejes',
            field=models.ManyToManyField(to='skateez.Ejes'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='rodamientos',
            field=models.ManyToManyField(to='skateez.Rodamientos'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='rueda',
            field=models.ManyToManyField(to='skateez.Ruedas'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='tabla',
            field=models.ManyToManyField(to='skateez.Tabla'),
        ),
    ]
