# Generated by Django 3.1.2 on 2020-10-16 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skateez', '0012_auto_20201016_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='ejes',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='ejes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skateez.ejes'),
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='rodamientos',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='rodamientos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skateez.rodamientos'),
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='rueda',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='rueda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skateez.ruedas'),
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='tabla',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='tabla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skateez.tabla'),
        ),
    ]
