# Generated by Django 3.1.2 on 2020-10-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skateez', '0014_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tabla',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Tabla'},
        ),
        migrations.AlterField(
            model_name='ejes',
            name='Cantidad',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='rodamientos',
            name='Cantidad',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='ruedas',
            name='Cantidad',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='tabla',
            name='Cantidad',
            field=models.IntegerField(default='0'),
        ),
        migrations.DeleteModel(
            name='author',
        ),
    ]
