# Generated by Django 3.1.2 on 2020-11-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skateez', '0017_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
