# Generated by Django 3.1.2 on 2020-11-20 18:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skateez', '0018_indexview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Usuario',
        ),
    ]
